### ISSUE TITLE
About the speed of Meta-Upsample

### ISSUE THREAD

**Issue by xiaobiaodu** [smallsunsun1/RDN#1]
Hi. I have test your code in B100 datasets by test.py(setting feature size is same with B100 ). 

In the paper of Meta-SR. the speed time of Upsacale is 3.6e-4s. 

But the speed time of yours is 0.04s.  

I think the problem is the tf.while_loop is very consume time.

I wonder that maybe you had fix this problem by using other ways?

**Comment by smallsunsun1** [comment]
Code in test.py is just for test the whether the code is correct and is out of data. The new implementation called batch_conv is in basemodel.py, when batch_size=1, I solved the problem of use conv operator in tf.while_loop instead of using tf.nn.depthwise_conv. The training speed can speed up a lot.
